name: Foundry CI

on:
  pull_request:
    branches:
      - main

jobs:

  # Add job timestamp
  print_timestamp: 
    runs-on: ubuntu-latest
    steps:
      - name: Generate timestamp
        run: |
          echo "TIMESTAMP=$(TZ='America/Los_Angeles' date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Print timestamp
        run: |
          echo "Execution time (Pacific Time Zone) $TIMESTAMP"

  foundry-test:
    strategy:
      fail-fast: true
    name: Foundry Unit Test
    runs-on: ubuntu-latest
    needs: print_timestamp
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: recursive
          fetch-depth: 0
          
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      # first, build contracts excluding the tests and scripts. Check contract sizes in this step.
      - name: Run Contract Size check
        run: |
          forge --version
          forge install OpenZeppelin/openzeppelin-foundry-upgrades
          forge build --force --sizes --skip test --skip script
      
      # This step requires full build to be run first
      - name: Upgrade Safety test
        run: |
          forge clean && forge build
          npx @openzeppelin/upgrades-core validate out/build-info

      - name: Run Forge tests
        run: |
          forge test -vvv --fork-url https://gateway.tenderly.co/public/sepolia --fork-block-number 5196000 --ffi --skip build
        id: forge-test

      - name: Run solhint
        run: npx solhint contracts/**/*.sol
